# Generated by Django 4.1.3 on 2022-11-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='text_article',
            field=models.TextField(verbose_name='Полное описание места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title_article',
            field=models.CharField(max_length=200, verbose_name='Короткое описание'),
        ),
    ]
