# Generated by Django 4.1.3 on 2022-11-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_place_text_article_alter_place_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title_article',
            field=models.TextField(max_length=200, verbose_name='Короткое описание'),
        ),
    ]
